language: go
go:
  - 1.2

before_install:
  - chmod +x *.sh
  - ./install-sdk.sh
  - export PATH=$PATH:$HOME/go_appengine

install:
  - goapp get github.com/qedus/nds
  - goapp get github.com/101loops/bdd
  - goapp get github.com/101loops/iszero
  - goapp get github.com/101loops/structor
  - goapp get code.google.com/p/go.tools/cmd/cover

script:
  - goapp test -v -covermode=count -coverprofile=profile.cov .

after_success:
  - go get -u github.com/mattn/goveralls
  - ~/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
