language: go
go:
  - 1.5
  - 1.6
  - 1.7

before_install:
  - chmod +x bin/*.sh
  - bin/install-sdk.sh
  - export PATH=$PATH:$HOME/go_appengine

install:
  - goapp get github.com/qedus/nds
  - goapp get github.com/stephanos/bdd
  - goapp get github.com/stephanos/iszero
  - goapp get github.com/stephanos/structor

script:
  - bin/test-coverage.sh

after_success:
  - go get -u github.com/mattn/goveralls
  - ~/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
