language: go
go:
  - 1.1
  - 1.2

before_script:
  - sh install-sdk.sh

install:
  - go get github.com/101loops/bdd
  - go get github.com/101loops/mcache
  - go get github.com/101loops/reflector

script:
  - goappengine/goapp test